server:
  port: 8080
eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      # 设置与eureka交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
      defaultZone: http://eureka7001.com:7001/eureka # 单机版
# 设置feign客户端超时时间（openFeign默认支持feign）
ribbon:
  # 指的是简历连接所用的时间，适用于玩过状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


# 开启feign日志
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cas.service.FeignService: debug
feign:
  client:
    config:
      yjm:
        connect-timeout: 60000
        readTimeout: 15000
      default:
        connect-timeout: 60000
        readTimeout: 3000
