server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: common_router # 路由ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-privider-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/getName/**   # 断言，路径相匹配的进行路由

        - id: common_router2 # 路由ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-privider-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/timeout/**   # 断言，路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

### 添加过滤器访问地址：http://localhost:9527/getName?uname=ww
### 没添加过滤器访问地址： http://localhost:9527/getName
