server:
  port: 9528
spring:
  application:
    name: cloudalibaba-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#        - id: common_router # 路由ID，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://nacos-payment-provider # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/getName/**   # 断言，路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: localhost:8848

### 添加过滤器访问地址：http://localhost:9527/getName?uname=ww
### 没添加过滤器访问地址： http://localhost:9527/getName